.headers on 
.mode box


-- 1. Create the table
CREATE TABLE showing_null (
    CustomerId INTEGER PRIMARY KEY,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Email TEXT,       -- This column can be NULL
    Phone TEXT        -- This column can be NULL
);

-- 2. Insert only the first two rows
INSERT INTO showing_null (CustomerId, FirstName, LastName, Email, Phone)
VALUES 
    (1, 'John', 'Doe', NULL, '9876543210'),
    (2, 'Jane', 'Smith', 'jane.smith@example.com', NULL);

-- 3. Query rows where Email is NULL
SELECT * 
FROM showing_null
WHERE Email IS NULL;


.print '--- Generated by Sayam Shrestha ---'