.headers on 
.mode box

SELECT 
    c.CustomerId,
    c.FirstName,
    c.LastName,
    i.InvoiceId,
    i.Total
FROM Customers c
LEFT JOIN Invoices i
ON c.CustomerId = i.CustomerId
LIMIT 15;


.print '--- Generated by Sayam Shrestha ---'