.headers on 
.mode box

SELECT 
    t.Name AS Track,
    il.UnitPrice,
    il.Quantity
FROM Tracks t
JOIN Invoice_items il
ON t.TrackId = il.TrackId
LIMIT 15;


.print '--- Generated by Sayam Shrestha ---'