.headers on 
.mode box

-- This will NOT work in SQLite
SELECT 
    c.FirstName,
    c.LastName,
    i.InvoiceId,
    i.Total
FROM Customers c
RIGHT JOIN Invoices i
ON c.CustomerId = i.CustomerId;



.print '--- Generated by Sayam Shrestha ---'