.headers on 
.mode box

--this also wont work on sqlite
SELECT 
    c.CustomerId, 
    c.FirstName, 
    c.LastName, 
    i.InvoiceId, 
    i.Total
FROM Customers c
FULL OUTER JOIN Invoices i
ON c.CustomerId = i.CustomerId;



.print '--- Generated by Sayam Shrestha ---'