.headers on 
.mode box

SELECT 
    TrackId,
    Name,
    (SELECT Name 
    FROM Genres 
    WHERE Genres.GenreId = Tracks.GenreId) AS GenreName
FROM Tracks
WHERE GenreId = 1 AND trackId <=15;


.print '--- Generated by Sayam Shrestha ---'