.headers on 
.mode box 

PRAGMA foreign_keys = ON;


CREATE TABLE Tracks (
    TrackId      INTEGER PRIMARY KEY,         -- Primary Key, automatically NOT NULL & UNIQUE
    Name         TEXT NOT NULL,              -- NOT NULL constraint
    AlbumId      INTEGER,                     -- Foreign key references Albums
    Composer     TEXT,
    Milliseconds INTEGER NOT NULL CHECK(Milliseconds > 0),  -- CHECK constraint
    UnitPrice    REAL NOT NULL CHECK(UnitPrice >= 0),       -- CHECK constraint
    CONSTRAINT UQ_TrackName UNIQUE(Name, AlbumId),          -- UNIQUE across combination of Name + AlbumId
    FOREIGN KEY (AlbumId) REFERENCES Albums(AlbumId)        -- Referential integrity
);

-- Violates NOT NULL, CHECK, and FOREIGN KEY
INSERT INTO Tracks (TrackId, Name, AlbumId, Milliseconds, UnitPrice)
VALUES (100, NULL, 999, -200, 1.29);


.print '--- Generated by Sayam Shrestha ---'