.headers on 
.mode box

SELECT name FROM tracks
WHERE trackid <= 10
ORDER BY UnitPrice ASC;

SELECT name FROM tracks 
WHERE trackid <=10
ORDER BY UnitPrice DESC;

.print '--- Generated by Sayam Shrestha ---'