.headers on 
.mode box

SELECT name, UnitPrice FROM tracks
WHERE trackid <= 10
ORDER BY UnitPrice ASC;

SELECT name, UnitPrice FROM tracks 
WHERE trackid <=10
ORDER BY UnitPrice DESC;

.print '--- Generated by Sayam Shrestha ---'