.headers on 
.mode box

SELECT
    TrackId,
    UnitPrice,
    Quantity,

    UnitPrice * Quantity      AS TotalPrice,          -- multiplication
    UnitPrice + 1             AS PriceWithServiceFee, -- addition
    UnitPrice - 0.5           AS DiscountedPrice,     -- subtraction
    UnitPrice / Quantity      AS PricePerUnit,        -- division
    Quantity % 2              AS RemainingAfterPairing -- modulus

FROM invoice_items
WHERE TrackId <= 10;



.print '--- Generated by Sayam Shrestha ---'