.headers on 
.mode box


SELECT 
    COUNT(*) AS TotalTracks,
    SUM(UnitPrice) AS TotalPriceOfTracks,
    AVG(UnitPrice) AS AvgTrackPrice,
    MIN(UnitPrice) AS CheapestTrack,
    MAX(UnitPrice) AS MostExpensiveTrack
FROM Tracks;



.print '--- Generated by Sayam Shrestha ---'