.headers on 
.mode box


SELECT 
    GenreId,
    COUNT(TrackId) AS TotalTracks,
    SUM(UnitPrice) AS TotalPriceOfTracks,
    AVG(UnitPrice) AS AvgTrackPrice
FROM Tracks
GROUP BY GenreId
ORDER BY TotalTracks DESC;



.print '--- Generated by Sayam Shrestha ---'