.headers on 
.mode box


SELECT 
    GenreId,
    COUNT(TrackId) AS TotalTracks,
    AVG(UnitPrice) AS AvgTrackPrice
FROM Tracks
GROUP BY GenreId
HAVING COUNT(TrackId) > 50
ORDER BY TotalTracks DESC;




.print '--- Generated by Sayam Shrestha ---'